// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreAPI.Service;

namespace StoreAPI.Service.Migrations
{
    [DbContext(typeof(CardCramContext))]
    [Migration("20210201023424_‘initial_commit’")]
    partial class initial_commit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CardCram.Domain.Models.Card", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeckEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityId");

                    b.HasIndex("DeckEntityId");

                    b.ToTable("Card");

                    b.HasData(
                        new
                        {
                            EntityId = 1,
                            Answer = "George Washington",
                            DeckEntityId = 1,
                            Question = "Who was the first president?"
                        });
                });

            modelBuilder.Entity("CardCram.Domain.Models.Deck", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("EntityId");

                    b.ToTable("Deck");

                    b.HasData(
                        new
                        {
                            EntityId = 1
                        });
                });

            modelBuilder.Entity("CardCram.Domain.Models.Card", b =>
                {
                    b.HasOne("CardCram.Domain.Models.Deck", "deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("deck");
                });

            modelBuilder.Entity("CardCram.Domain.Models.Deck", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
